const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={route:'casino',filter:'all',provider:'all',favorites:new Set(),sound:true,lastFocus:null};
const routes={casino:'Casino',live:'Live',providers:'Провайдеры',promotions:'Промо',tournaments:'Турниры',favorites:'Избранное',history:'История',profile:'Профиль',support:'Помощь',responsible:'Ответственная игра'};
const games=[
 ['crazy-time','Crazy Time','Evolution Gaming','live','LIVE','CT','#ff6677','#4a2d4d'],['dream-catcher','Dream Catcher','Evolution Gaming','live','LIVE','DC','#9279ff','#25264f'],['sweet-bonanza','Sweet Bonanza 1000','Pragmatic Play','hot','HOT','99','#ff7daf','#5b2c80'],['mega-wheel','Mega Wheel','Pragmatic Live','live','LIVE','MW','#64ddff','#24345a'],['dog-house','The Dog House','Pragmatic Play','hot','HOT','DH','#ffa15e','#5d3b22'],['gates','Gates of Olympus','Pragmatic Play','hot','','Ω','#947cff','#312855'],['le-bandit','Le Bandit','Hacksaw','hot','HOT','LB','#c8ff3d','#20462f'],['wanted','Wanted Dead or a Wild','Hacksaw','hot','HOT','W','#ff9b5c','#55281b'],['money-train','Money Train 4','Relax Gaming','new','NEW','M4','#5ce8ff','#173d54'],['san-quentin','San Quentin xWays','No Limit City','new','NEW','SQ','#b7a9ff','#2b2857'],['blackjack-vip','Blackjack VIP','Pragmatic Live','live','LIVE','21','#c8ff3d','#234830'],['roulette','Lightning Roulette','Evolution Gaming','live','LIVE','⚡','#5ce8ff','#282f68']
].map(([id,name,provider,type,tag,symbol,g1,g2])=>({id,name,provider,type,tag,symbol,g1,g2}));
const providerCounts=[['Evolution Gaming',141],['Pragmatic Play',678],['Pragmatic Live',294],['Hacksaw',250],['Relax Gaming',115],['No Limit City',137],['PlayNGo',366],['NetEnt',243],['BGaming',299],['Red Tiger',378],['Spinomenal',725],['Yggdrasil',184]];
const promos=[['Weekly Collection','CURRENT','Подборка актуального контента и условий в отдельном блоке.'],['Provider Spotlight','FEATURED','Промо провайдера не смешано с основным каталогом.'],['Seasonal Program','INFO','Сезонный раздел с прозрачным описанием периода и условий.']];
const events=[['Slots Race','ACTIVE','Текущий период','Правила и условия доступны в карточке события.'],['Studio Series','UPCOMING','Следующий период','Отдельный экран события без агрессивного таймера.'],['Live Weekend','INFO','Расписание','Информация о формате и доступных разделах.']];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])), norm=v=>String(v).trim().toLocaleLowerCase('ru-RU');
const head=(e,t,d)=>`<div class="page-head"><div><span class="eyebrow">${esc(e)}</span><h1>${esc(t)}</h1><p>${esc(d)}</p></div></div>`;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1500)}
function gameCard(g){const fav=state.favorites.has(g.id),cls=g.tag==='LIVE'?'live':g.tag==='HOT'?'hot':'new';return `<article class="game-card" tabindex="0" role="button" data-game="${esc(g.id)}" aria-label="Открыть ${esc(g.name)}" style="--g1:${g.g1};--g2:${g.g2}"><div class="game-art"></div>${g.tag?`<span class="game-tag ${cls}">${g.tag}</span>`:''}<button class="favorite ${fav?'on':''}" type="button" data-fav="${esc(g.id)}" aria-label="${fav?'Удалить из избранного':'Добавить в избранное'}">${fav?'♥':'♡'}</button><div class="game-symbol">${esc(g.symbol)}</div><div class="game-meta"><b>${esc(g.name)}</b><small>${esc(g.provider)}</small></div></article>`}
function filtered(){return games.filter(g=>(state.filter==='all'||g.type===state.filter||state.filter==='favorites'&&state.favorites.has(g.id))&&(state.provider==='all'||g.provider===state.provider))}
function catalog(){const list=filtered();return `<div class="section-title"><div><span class="eyebrow">КАТАЛОГ</span><h2>Игры</h2></div><div class="game-toolbar">${[['all','Все'],['hot','Популярные'],['new','Новые'],['live','Live'],['favorites','♡ Избранное']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" type="button" data-filter="${v}">${l}</button>`).join('')}</div></div><div class="game-grid" id="gameGrid">${list.length?list.map(gameCard).join(''):`<div class="empty-state" style="grid-column:1/-1"><div><div class="empty-icon">⌕</div><h3>Игр не найдено</h3><p>Сбросьте фильтр или выберите другого провайдера.</p><button class="btn soft" data-reset type="button">Сбросить</button></div></div>`}</div>`}
function providers(withSearch=true){return `<section class="provider-section"><div class="provider-head"><div><span class="eyebrow">ПРОВАЙДЕРЫ</span><h2 style="margin:5px 0 0">Каталог</h2></div>${withSearch?`<label class="provider-search" for="providerSearch"><span>⌕</span><input id="providerSearch" placeholder="Найти провайдера"></label>`:''}</div><div class="provider-chips" id="providerChips">${providerCounts.map(([n,c])=>`<button class="provider-chip ${state.provider===n?'active':''}" type="button" data-provider="${esc(n)}"><span style="color:inherit;font-size:inherit">${esc(n)}</span><span>${c}</span></button>`).join('')}</div></section>`}
function casino(){return `${head('ZOOMA CASINO','Casino','Знакомая структура ZOOMA с более чистой и предсказуемой навигацией.')}<section class="hero-layout"><article class="hero-card"><div class="hero-copy"><span class="eyebrow">ZOOMA · REBUILT</span><h1>Всё казино.<br><span>В одной системе.</span></h1><p>Каталог, live-раздел, провайдеры, промо и события собраны в единую кликабельную структуру.</p><div class="hero-actions"><button class="btn primary" data-scroll type="button">Открыть каталог</button><a class="btn soft route-link" href="#tournaments" data-route="tournaments">События</a></div></div><div class="hero-visual" aria-hidden="true"><div class="orbit a"></div><div class="orbit b"></div><div class="orbit c"></div><div class="z-core">Z</div><div class="float-pill p1">CASINO</div><div class="float-pill p2">LIVE</div><div class="float-pill p3">ZOOMA</div></div></article><div class="side-stack"><article class="feature-card" tabindex="0" role="button" data-go="live"><span class="eyebrow">LIVE</span><div class="big-number">Live Casino</div><p>Отдельная витрина live-контента.</p></article><article class="feature-card" tabindex="0" role="button" data-go="promotions"><span class="eyebrow">PROMO</span><div class="big-number">Promotions</div><p>Предложения не смешаны с каталогом.</p></article></div></section>${catalog()}${providers()}`}
function live(){return `${head('LIVE CASINO','Live','Live-контент выделен в самостоятельный раздел и остаётся частью общей системы ZOOMA.')}<div class="game-grid">${games.filter(g=>g.type==='live').map(gameCard).join('')}</div>`}
function providersPage(){return `${head('КАТАЛОГ','Провайдеры','Выберите провайдера — каталог откроется уже с нужным фильтром.')}${providers(false)}`}
function infoCards(items,kind){return `<div class="cards-grid">${items.map(([t,s,m,c=''])=>`<article class="content-card actionable" tabindex="0" role="button" data-info-title="${esc(t)}" data-info-copy="${esc(c||m)}"><span class="status-pill ${s==='UPCOMING'?'cyan':''}">${esc(s)}</span><h3>${esc(t)}</h3><p>${esc(c||m)}</p><div class="meta"><span>${kind==='event'?esc(m):'Подробнее'}</span><span>→</span></div></article>`).join('')}</div>`}
function promotions(){return `${head('PROMOTIONS','Промо','Промо-материалы вынесены из каталога в отдельную понятную витрину.')}${infoCards(promos,'promo')}`}
function tournaments(){return `${head('EVENTS','Турниры','Статус, период и правила показаны без лишнего визуального давления.')}${infoCards(events,'event')}`}
function favorites(){const list=games.filter(g=>state.favorites.has(g.id));return `${head('ACCOUNT','Избранное','Сохранённые карточки доступны в одном месте.')}<div class="game-grid">${list.length?list.map(gameCard).join(''):`<div class="empty-state" style="grid-column:1/-1"><div><div class="empty-icon">♡</div><h3>Избранное пусто</h3><p>Добавьте карточки через значок сердца.</p><a class="btn soft route-link" href="#casino" data-route="casino">В каталог</a></div></div>`}</div>`}
function history(){return `${head('ACCOUNT','История','Демонстрационный экран истории аккаунта.')}<div class="empty-state"><div><div class="empty-icon">↺</div><h3>История пока пуста</h3><p>В production здесь отображаются реальные данные пользователя.</p></div></div>`}
function profile(){const cards=[['Безопасность','Защита аккаунта','Пароль, двухфакторная аутентификация и активные сессии.','info'],['История','Активность','История аккаунта.','history'],['Контроль','Лимиты и паузы','Инструменты контроля.','responsible'],['Поддержка','Помощь','FAQ и каналы поддержки.','support']];return `${head('ACCOUNT','Профиль','Настройки, безопасность и помощь без тупиковых экранов.')}<div class="profile-grid">${cards.map(([s,b,c,r])=>`<article class="profile-card" tabindex="0" role="button" ${r==='info'?`data-info-title="${s}" data-info-copy="${c}"`:`data-go="${r}"`}><span>${s}</span><b>${b}</b><small>${c}</small></article>`).join('')}</div>`}
function support(){const qa=[['Как работает поиск?','Поиск фильтрует демонстрационный каталог по названию и провайдеру.'],['Почему игра не запускается?','Это redesign-прототип. Реальные launcher-ссылки намеренно не подключены.'],['Где находятся лимиты?','Инструменты контроля вынесены в раздел «Ответственная игра».']];return `${head('SUPPORT','Помощь','FAQ и понятные пути к ключевым разделам продукта.')}<div class="faq-list">${qa.map(([q,a])=>`<article class="faq-item"><button type="button"><span>${esc(q)}</span><span>+</span></button><div>${esc(a)}</div></article>`).join('')}</div>`}
function responsible(){return `${head('18+','Ответственная игра','Инструменты контроля должны быть доступны напрямую и без скрытых препятствий.')}<div class="cards-grid"><article class="content-card"><span class="status-pill">LIMITS</span><h3>Лимиты</h3><p>Место для пользовательских ограничений.</p></article><article class="content-card"><span class="status-pill cyan">BREAK</span><h3>Пауза</h3><p>Понятный сценарий временной паузы.</p></article><article class="content-card"><span class="status-pill">SUPPORT</span><h3>Поддержка</h3><p>Прямой доступ к справочной информации.</p></article></div>`}
const views={casino,live,providers:providersPage,promotions,tournaments,favorites,history,profile,support,responsible};
function sync(route){$$('.route-link').forEach(a=>{const active=a.dataset.route===route;a.classList.toggle('active',active);active?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});$('#breadcrumb').innerHTML=`<span>ZOOMA</span><i>/</i><strong>${esc(routes[route])}</strong>`;document.title=`${routes[route]} — ZOOMA`}
function setRoute(route,push=false){route=routes[route]?route:'casino';state.route=route;if(push&&location.hash!==`#${route}`)history.pushState(null,'',`#${route}`);$('#pageView').innerHTML=views[route]();$('#pageView').classList.remove('page-enter');void $('#pageView').offsetWidth;$('#pageView').classList.add('page-enter');sync(route);bind();$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.remove('open');scrollTo({top:0,behavior:'auto'})}
function openModal(html,focus='button,input'){state.lastFocus=document.activeElement;$('#modalContent').innerHTML=html;$('#modalLayer').classList.add('open');$('#modalLayer').setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden';requestAnimationFrame(()=>$(focus,$('#modalContent'))?.focus())}
function closeModal(){$('#modalLayer').classList.remove('open');$('#modalLayer').setAttribute('aria-hidden','true');document.documentElement.style.overflow='';state.lastFocus?.focus?.()}
function info(t,c){openModal(`<div class="modal-head"><div><span class="eyebrow">ZOOMA</span><h2 id="modalTitle">${esc(t)}</h2></div><button class="icon-btn" type="button" data-close-modal aria-label="Закрыть">×</button></div><p class="modal-copy">${esc(c)}</p><div class="modal-actions"><button class="btn primary" type="button" data-close-modal>Понятно</button></div>`)}
function openGame(id){const g=games.find(x=>x.id===id);if(!g)return;openModal(`<div class="game-card" aria-hidden="true" style="--g1:${g.g1};--g2:${g.g2};max-width:220px;margin:0 auto 20px"><div class="game-art"></div><div class="game-symbol">${esc(g.symbol)}</div><div class="game-meta"><b>${esc(g.name)}</b><small>${esc(g.provider)}</small></div></div><div class="modal-head"><div><span class="eyebrow">${esc(g.provider)}</span><h2 id="modalTitle">${esc(g.name)}</h2></div><button class="icon-btn" type="button" data-close-modal aria-label="Закрыть">×</button></div><p class="modal-copy">Информационная карточка redesign-прототипа. Реальный запуск игры и финансовые действия не подключены.</p><div class="modal-actions"><button class="btn soft" data-close-modal type="button">Закрыть</button><button class="btn primary" data-provider-modal="${esc(g.provider)}" type="button">Другие игры провайдера</button></div>`);$('[data-provider-modal]')?.addEventListener('click',e=>{state.provider=e.currentTarget.dataset.providerModal;state.filter='all';closeModal();setRoute('casino',true)})}
function auth(mode){openModal(`<div class="modal-head"><div><span class="eyebrow">ACCOUNT</span><h2 id="modalTitle">${mode==='register'?'Создать аккаунт':'Войти'}</h2></div><button class="icon-btn" type="button" data-close-modal aria-label="Закрыть">×</button></div><p class="modal-copy">Демонстрационная форма. Отправка данных отключена.</p><form class="form-grid" id="demoAuth"><label class="field"><span>Email</span><input type="email" required autocomplete="email" placeholder="name@example.com"></label><label class="field"><span>Пароль</span><input type="password" required autocomplete="current-password" placeholder="••••••••"></label><button class="btn primary full" type="submit">Продолжить</button></form>`);$('#demoAuth').addEventListener('submit',e=>{e.preventDefault();toast('Demo: отправка отключена');closeModal()})}
function bindGames(){$$('[data-game]').forEach(card=>{const open=()=>openGame(card.dataset.game);card.addEventListener('click',e=>{if(!e.target.closest('[data-fav]'))open()});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('[data-fav]')){e.preventDefault();open()}})});$$('[data-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const id=b.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);toast(state.favorites.has(id)?'Добавлено в избранное':'Удалено из избранного');setRoute(state.route)}))}
function bind(){bindGames();$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.filter;setRoute(state.route)}));$('[data-reset]')?.addEventListener('click',()=>{state.filter='all';state.provider='all';setRoute('casino')});$('[data-scroll]')?.addEventListener('click',()=>$('#gameGrid')?.scrollIntoView({behavior:'smooth'}));$$('[data-go]').forEach(el=>{const go=()=>setRoute(el.dataset.go,true);el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});$$('[data-info-title]').forEach(el=>{const go=()=>info(el.dataset.infoTitle,el.dataset.infoCopy);el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});$$('[data-provider]').forEach(b=>b.addEventListener('click',()=>{state.provider=state.provider===b.dataset.provider?'all':b.dataset.provider;state.filter='all';setRoute('casino',true)}));$('#providerSearch')?.addEventListener('input',e=>{const q=norm(e.target.value);$$('#providerChips [data-provider]').forEach(b=>b.hidden=!norm(b.dataset.provider).includes(q))});$$('.faq-item button').forEach(b=>b.addEventListener('click',()=>b.closest('.faq-item').classList.toggle('open')))}
function search(value,target='#searchResults'){const box=$(target),q=norm(value);if(!q){box.innerHTML='';box.classList.remove('open');return}const list=games.filter(g=>norm(`${g.name} ${g.provider}`).includes(q)).slice(0,7);box.innerHTML=list.length?list.map(g=>`<button class="search-row" type="button" data-search-game="${esc(g.id)}"><b>${esc(g.name)}</b><small>${esc(g.provider)}</small></button>`).join(''):`<div class="search-row"><small>Ничего не найдено</small></div>`;box.classList.add('open');$$('[data-search-game]',box).forEach(b=>b.addEventListener('click',()=>{box.classList.remove('open');openGame(b.dataset.searchGame)}))}
function init(){document.addEventListener('click',e=>{const r=e.target.closest('.route-link');if(r){e.preventDefault();setRoute(r.dataset.route,true);return}const m=e.target.closest('[data-modal]');if(m){auth(m.dataset.modal);return}if(e.target.closest('[data-close-modal]'))closeModal()});$('#menuBtn').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#sidebarBackdrop').classList.add('open')});$('#sidebarBackdrop').addEventListener('click',()=>{$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.remove('open')});$('#soundToggle').addEventListener('click',()=>{state.sound=!state.sound;$('#soundState').textContent=state.sound?'ON':'OFF';toast(`Звук ${state.sound?'включён':'выключен'}`)});$('#globalSearch').addEventListener('input',e=>search(e.target.value));$('#mobileSearch').addEventListener('click',()=>{openModal(`<div class="modal-head"><div><span class="eyebrow">SEARCH</span><h2 id="modalTitle">Поиск</h2></div><button class="icon-btn" type="button" data-close-modal aria-label="Закрыть">×</button></div><label class="field"><span>Игра или провайдер</span><input id="mobileSearchInput" type="search" placeholder="Начните вводить…"></label><div id="mobileSearchResults"></div>`,'#mobileSearchInput');$('#mobileSearchInput').addEventListener('input',e=>search(e.target.value,'#mobileSearchResults'))});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#modalLayer').classList.contains('open'))closeModal();$('#searchResults').classList.remove('open');$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.remove('open')}if(e.key==='/'&&!/input|textarea/i.test(document.activeElement.tagName)&&innerWidth>720){e.preventDefault();$('#globalSearch').focus()}});window.addEventListener('popstate',()=>setRoute((location.hash||'#casino').slice(1).split('?')[0]));window.addEventListener('hashchange',()=>setRoute((location.hash||'#casino').slice(1).split('?')[0]));setRoute((location.hash||'#casino').slice(1).split('?')[0])}
init();
