const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={route:'casino',filter:'all',provider:'all',favorites:new Set(),sound:true,lastFocus:null};
const routes={casino:'Casino',wheel:'Wheel',mines:'Mines',classic:'Classic',duels:'Duels',tournaments:'Турниры',trains:'The Trains!',promo:'Промокод',live:'Live',providers:'Провайдеры',promotions:'Промо',favorites:'Избранное',history:'История',profile:'Профиль',support:'Вопросы и ответы',responsible:'Ответственная игра'};
const raw=[
['crazy-time','Crazy Time','Evolution Gaming','live','LIVE','CT','#ff6677','#4a2d4d'],['dream-catcher','Dream Catcher','Evolution Gaming','live','LIVE','DC','#9279ff','#25264f'],['sweet-bonanza','Sweet Bonanza 1000','Pragmatic Play','hot','HOT','99','#ff7daf','#5b2c80'],['mega-wheel','Mega Wheel','Pragmatic Live','live','LIVE','MW','#64ddff','#24345a'],['dog-house','The Dog House','Pragmatic Play','hot','HOT','DH','#ffa15e','#5d3b22'],['gates','Gates of Olympus','Pragmatic Play','hot','','Ω','#947cff','#312855'],['le-bandit','Le Bandit','Hacksaw','hot','HOT','LB','#c8ff3d','#20462f'],['wanted','Wanted Dead or a Wild','Hacksaw','hot','HOT','W','#ff9b5c','#55281b'],['money-train','Money Train 4','Relax Gaming','new','NEW','M4','#5ce8ff','#173d54'],['san-quentin','San Quentin xWays','No Limit City','new','NEW','SQ','#b7a9ff','#2b2857'],['blackjack-vip','Blackjack VIP','Pragmatic Live','live','LIVE','21','#c8ff3d','#234830'],['roulette','Lightning Roulette','Evolution Gaming','live','LIVE','⚡','#5ce8ff','#282f68']];
const games=raw.map(([id,name,provider,type,tag,symbol,g1,g2])=>({id,name,provider,type,tag,symbol,g1,g2}));
const providers=[['Evolution Gaming',141],['Pragmatic Play',678],['Pragmatic Live',294],['Hacksaw',250],['Relax Gaming',115],['No Limit City',137],['PlayNGo',366],['NetEnt',243],['BGaming',299],['Red Tiger',378],['Spinomenal',725],['Yggdrasil',184]];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),norm=v=>String(v).trim().toLowerCase();
const head=(e,t,d)=>`<div class="page-head"><div><span class="eyebrow">${e}</span><h1>${t}</h1><p>${d}</p></div></div>`;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),1500)}
function card(g){const fav=state.favorites.has(g.id),cls=g.tag==='LIVE'?'live':g.tag==='HOT'?'hot':'new';return `<article class="game-card" tabindex="0" role="button" data-game="${g.id}" aria-label="Открыть ${esc(g.name)}" style="--g1:${g.g1};--g2:${g.g2}"><div class="game-art"></div>${g.tag?`<span class="game-tag ${cls}">${g.tag}</span>`:''}<button class="favorite ${fav?'on':''}" type="button" data-fav="${g.id}" aria-label="${fav?'Удалить из избранного':'Добавить в избранное'}">${fav?'♥':'♡'}</button><div class="game-symbol">${g.symbol}</div><div class="game-meta"><b>${esc(g.name)}</b><small>${esc(g.provider)}</small></div></article>`}
function filtered(){return games.filter(g=>(state.filter==='all'||g.type===state.filter||state.filter==='favorites'&&state.favorites.has(g.id))&&(state.provider==='all'||g.provider===state.provider))}
function catalog(){const list=filtered();return `<div class="section-title"><div><span class="eyebrow">КАТАЛОГ</span><h2>Игры</h2></div><div class="game-toolbar">${[['all','Все'],['hot','Популярные'],['new','Новые'],['live','Live'],['favorites','♡ Избранное']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" data-filter="${v}" type="button">${l}</button>`).join('')}</div></div><div class="game-grid" id="gameGrid">${list.length?list.map(card).join(''):`<div class="empty-state" style="grid-column:1/-1"><div><div class="empty-icon">⌕</div><h3>Игр не найдено</h3><p>Сбросьте фильтры.</p><button class="btn soft" data-reset type="button">Сбросить</button></div></div>`}</div>`}
function providerBlock(search=true){return `<section class="provider-section"><div class="provider-head"><div><span class="eyebrow">ПРОВАЙДЕРЫ</span><h2 style="margin:5px 0 0">Каталог</h2></div>${search?`<label class="provider-search" for="providerSearch"><span>⌕</span><input id="providerSearch" placeholder="Найти провайдера"></label>`:''}</div><div class="provider-chips" id="providerChips">${providers.map(([n,c])=>`<button class="provider-chip ${state.provider===n?'active':''}" data-provider="${esc(n)}" type="button"><span style="color:inherit;font-size:inherit">${esc(n)}</span><span>${c}</span></button>`).join('')}</div></section>`}
function casino(){return `${head('ZOOMA CASINO','Casino','Знакомая структура ZOOMA с более чистой и предсказуемой навигацией.')}<section class="hero-layout"><article class="hero-card"><div class="hero-copy"><span class="eyebrow">ZOOMA · REBUILT</span><h1>Всё казино.<br><span>В одной системе.</span></h1><p>Каталог, игровые разделы, провайдеры, промо и события собраны в единую кликабельную структуру.</p><div class="hero-actions"><button class="btn primary" data-scroll type="button">Открыть каталог</button><a class="btn soft route-link" href="#tournaments" data-route="tournaments">События</a></div></div><div class="hero-visual" aria-hidden="true"><div class="orbit a"></div><div class="orbit b"></div><div class="orbit c"></div><div class="z-core">Z</div><div class="float-pill p1">CASINO</div><div class="float-pill p2">LIVE</div><div class="float-pill p3">ZOOMA</div></div></article><div class="side-stack"><article class="feature-card" tabindex="0" role="button" data-go="wheel"><span class="eyebrow">GAME</span><div class="big-number">Wheel</div><p>Сохранённый раздел основной структуры.</p></article><article class="feature-card" tabindex="0" role="button" data-go="promotions"><span class="eyebrow">PROMO</span><div class="big-number">Promotions</div><p>Предложения отдельно от каталога.</p></article></div></section>${catalog()}${providerBlock()}`}
function product(label,icon,copy){return `${head('ZOOMA GAME',label,copy)}<section class="hero-layout"><article class="hero-card"><div class="hero-copy"><span class="eyebrow">${label.toUpperCase()}</span><h1>${label}</h1><p>Структура раздела сохранена. В redesign-прототипе реальная игровая логика и ставки не подключены.</p><div class="hero-actions"><a class="btn soft route-link" href="#casino" data-route="casino">Вернуться в Casino</a></div></div><div class="hero-visual" aria-hidden="true"><div class="orbit a"></div><div class="orbit b"></div><div class="z-core">${icon}</div></div></article></section>`}
const wheel=()=>product('Wheel','W','Отдельный игровой раздел Wheel из основной структуры ZOOMA.');
const mines=()=>product('Mines','M','Раздел Mines сохранён как самостоятельный экран.');
const classic=()=>product('Classic','C','Classic остаётся доступен из основной навигации.');
const duels=()=>product('Duels','D','Раздел Duels сохранён и больше не является тупиковой ссылкой.');
function live(){return `${head('LIVE CASINO','Live','Live-контент выделен в самостоятельный раздел.')}<div class="game-grid">${games.filter(g=>g.type==='live').map(card).join('')}</div>`}
function providersPage(){return `${head('КАТАЛОГ','Провайдеры','Выберите провайдера — каталог откроется с нужным фильтром.')}${providerBlock(false)}`}
function infoGrid(items){return `<div class="cards-grid">${items.map(([t,s,c])=>`<article class="content-card actionable" tabindex="0" role="button" data-info-title="${esc(t)}" data-info-copy="${esc(c)}"><span class="status-pill ${s==='UPCOMING'?'cyan':''}">${s}</span><h3>${esc(t)}</h3><p>${esc(c)}</p><div class="meta"><span>Подробнее</span><span>→</span></div></article>`).join('')}</div>`}
function promotions(){return `${head('PROMOTIONS','Промо','Промо вынесены из каталога в отдельную витрину.')}${infoGrid([['Weekly Collection','CURRENT','Актуальная подборка с отдельными условиями.'],['Provider Spotlight','FEATURED','Тематическая подборка контента провайдера.'],['Seasonal Program','INFO','Сезонный информационный блок.']])}`}
function tournaments(){return `${head('EVENTS','Турниры','Статус и правила показаны без визуального давления.')}${infoGrid([['Slots Race','ACTIVE','Текущий период и правила события.'],['Studio Series','UPCOMING','Следующий период и условия.'],['Live Weekend','INFO','Информация о формате события.']])}`}
function trains(){return `${head('ZOOMA EVENT','The Trains!','Раздел сохранён как самостоятельная информационная страница.')}<div class="cards-grid"><article class="content-card"><span class="status-pill">INFO</span><h3>Current train</h3><p>Структура без участия и финансовых действий.</p></article><article class="content-card"><span class="status-pill cyan">HISTORY</span><h3>История</h3><p>Место для истории событий.</p></article></div>`}
function promo(){return `${head('PROMOCODE','Промокод','Поле сохранено, реальная активация в demo отключена.')}<article class="content-card" style="max-width:620px"><span class="status-pill">DEMO</span><h3>Активировать промокод</h3><form class="form-grid" id="promoForm"><label class="field"><span>Промокод</span><input maxlength="32" placeholder="Введите код"></label><button class="btn primary" type="submit">Активировать</button></form></article>`}
function favorites(){const list=games.filter(g=>state.favorites.has(g.id));return `${head('ACCOUNT','Избранное','Сохранённые карточки в одном месте.')}<div class="game-grid">${list.length?list.map(card).join(''):`<div class="empty-state" style="grid-column:1/-1"><div><div class="empty-icon">♡</div><h3>Избранное пусто</h3><p>Добавьте карточки через сердце.</p><a class="btn soft route-link" href="#casino" data-route="casino">В каталог</a></div></div>`}</div>`}
function history(){return `${head('ACCOUNT','История','Демонстрационный экран истории аккаунта.')}<div class="empty-state"><div><div class="empty-icon">↺</div><h3>История пока пуста</h3><p>В production здесь будут реальные данные пользователя.</p></div></div>`}
function profile(){return `${head('ACCOUNT','Профиль','Настройки, безопасность и помощь без тупиковых экранов.')}<div class="profile-grid">${[['Безопасность','Защита аккаунта','Пароль, 2FA и сессии.','info'],['История','Активность','История аккаунта.','history'],['Контроль','Лимиты и паузы','Инструменты контроля.','responsible'],['Поддержка','Помощь','FAQ и каналы поддержки.','support']].map(([s,b,c,r])=>`<article class="profile-card" tabindex="0" role="button" ${r==='info'?`data-info-title="${s}" data-info-copy="${c}"`:`data-go="${r}"`}><span>${s}</span><b>${b}</b><small>${c}</small></article>`).join('')}</div>`}
function support(){return `${head('SUPPORT','Вопросы и ответы','FAQ и понятные пути к ключевым разделам.')}<div class="faq-list">${[['Как работает поиск?','Поиск фильтрует demo-каталог по названию и провайдеру.'],['Почему игра не запускается?','Это redesign-прототип; реальные launcher-ссылки не подключены.'],['Где лимиты?','Инструменты контроля находятся в «Ответственной игре».']].map(([q,a])=>`<article class="faq-item"><button type="button"><span>${q}</span><span>+</span></button><div>${a}</div></article>`).join('')}</div>`}
function responsible(){return `${head('18+','Ответственная игра','Инструменты контроля доступны напрямую.')}<div class="cards-grid"><article class="content-card"><span class="status-pill">LIMITS</span><h3>Лимиты</h3><p>Место для пользовательских ограничений.</p></article><article class="content-card"><span class="status-pill cyan">BREAK</span><h3>Пауза</h3><p>Понятный сценарий временной паузы.</p></article><article class="content-card"><span class="status-pill">SUPPORT</span><h3>Поддержка</h3><p>Прямой доступ к справочной информации.</p></article></div>`}
const views={casino,wheel,mines,classic,duels,tournaments,trains,promo,live,providers:providersPage,promotions,favorites,history,profile,support,responsible};
function sync(r){$$('.route-link').forEach(a=>{const on=a.dataset.route===r;a.classList.toggle('active',on);on?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});$('#breadcrumb').innerHTML=`<span>ZOOMA</span><i>/</i><strong>${routes[r]}</strong>`;document.title=`${routes[r]} — ZOOMA`}
function go(r,push=false){r=routes[r]?r:'casino';state.route=r;if(push&&location.hash!==`#${r}`)history.pushState(null,'',`#${r}`);$('#pageView').innerHTML=views[r]();sync(r);bind();$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.remove('open');scrollTo({top:0,behavior:'auto'})}
function modal(html,focus='button,input'){state.lastFocus=document.activeElement;$('#modalContent').innerHTML=html;$('#modalLayer').classList.add('open');$('#modalLayer').setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden';requestAnimationFrame(()=>$(focus,$('#modalContent'))?.focus())}
function closeModal(){$('#modalLayer').classList.remove('open');$('#modalLayer').setAttribute('aria-hidden','true');document.documentElement.style.overflow='';state.lastFocus?.focus?.()}
function info(t,c){modal(`<div class="modal-head"><div><span class="eyebrow">ZOOMA</span><h2 id="modalTitle">${esc(t)}</h2></div><button class="icon-btn" data-close-modal type="button" aria-label="Закрыть">×</button></div><p class="modal-copy">${esc(c)}</p><div class="modal-actions"><button class="btn primary" data-close-modal type="button">Понятно</button></div>`)}
function game(id){const g=games.find(x=>x.id===id);if(!g)return;modal(`<div class="modal-head"><div><span class="eyebrow">${esc(g.provider)}</span><h2 id="modalTitle">${esc(g.name)}</h2></div><button class="icon-btn" data-close-modal type="button" aria-label="Закрыть">×</button></div><p class="modal-copy">Информационная карточка redesign-прототипа. Реальный запуск игры и финансовые действия не подключены.</p><div class="modal-actions"><button class="btn soft" data-close-modal type="button">Закрыть</button><button class="btn primary" data-provider-modal="${esc(g.provider)}" type="button">Другие игры провайдера</button></div>`);$('[data-provider-modal]')?.addEventListener('click',e=>{state.provider=e.currentTarget.dataset.providerModal;state.filter='all';closeModal();go('casino',true)})}
function auth(mode){modal(`<div class="modal-head"><div><span class="eyebrow">ACCOUNT</span><h2 id="modalTitle">${mode==='register'?'Создать аккаунт':'Войти'}</h2></div><button class="icon-btn" data-close-modal type="button" aria-label="Закрыть">×</button></div><p class="modal-copy">Демонстрационная форма. Отправка данных отключена.</p><form class="form-grid" id="demoAuth"><label class="field"><span>Email</span><input type="email" required></label><label class="field"><span>Пароль</span><input type="password" required></label><button class="btn primary full" type="submit">Продолжить</button></form>`);$('#demoAuth').addEventListener('submit',e=>{e.preventDefault();toast('Demo: отправка отключена');closeModal()})}
function bind(){$$('[data-game]').forEach(c=>{const o=()=>game(c.dataset.game);c.onclick=e=>{if(!e.target.closest('[data-fav]'))o()};c.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('[data-fav]')){e.preventDefault();o()}}});$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);toast(state.favorites.has(id)?'Добавлено в избранное':'Удалено из избранного');go(state.route)});$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;go(state.route)});$('[data-reset]')?.addEventListener('click',()=>{state.filter='all';state.provider='all';go('casino')});$('[data-scroll]')?.addEventListener('click',()=>$('#gameGrid')?.scrollIntoView({behavior:'smooth'}));$$('[data-go]').forEach(e=>{const f=()=>go(e.dataset.go,true);e.onclick=f;e.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();f()}}});$$('[data-info-title]').forEach(e=>{const f=()=>info(e.dataset.infoTitle,e.dataset.infoCopy);e.onclick=f;e.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();f()}}});$$('[data-provider]').forEach(b=>b.onclick=()=>{state.provider=state.provider===b.dataset.provider?'all':b.dataset.provider;state.filter='all';go('casino',true)});$('#providerSearch')?.addEventListener('input',e=>{const q=norm(e.target.value);$$('#providerChips [data-provider]').forEach(b=>b.hidden=!norm(b.dataset.provider).includes(q))});$$('.faq-item button').forEach(b=>b.onclick=()=>b.closest('.faq-item').classList.toggle('open'));$('#promoForm')?.addEventListener('submit',e=>{e.preventDefault();toast('Demo: активация отключена')})}
function search(v,target='#searchResults'){const box=$(target),q=norm(v);if(!q){box.innerHTML='';box.classList.remove('open');return}const list=games.filter(g=>norm(`${g.name} ${g.provider}`).includes(q)).slice(0,7);box.innerHTML=list.length?list.map(g=>`<button class="search-row" data-search-game="${g.id}" type="button"><b>${esc(g.name)}</b><small>${esc(g.provider)}</small></button>`).join(''):`<div class="search-row"><small>Ничего не найдено</small></div>`;box.classList.add('open');$$('[data-search-game]',box).forEach(b=>b.onclick=()=>{box.classList.remove('open');game(b.dataset.searchGame)})}
function init(){document.addEventListener('click',e=>{const r=e.target.closest('.route-link');if(r){e.preventDefault();go(r.dataset.route,true);return}const m=e.target.closest('[data-modal]');if(m){auth(m.dataset.modal);return}if(e.target.closest('[data-close-modal]'))closeModal()});$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#sidebarBackdrop').classList.add('open')};$('#sidebarBackdrop').onclick=()=>{$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.remove('open')};$('#soundToggle').onclick=()=>{state.sound=!state.sound;$('#soundState').textContent=state.sound?'ON':'OFF';toast(`Звук ${state.sound?'включён':'выключен'}`)};$('#globalSearch').oninput=e=>search(e.target.value);$('#mobileSearch').onclick=()=>{modal(`<div class="modal-head"><div><span class="eyebrow">SEARCH</span><h2 id="modalTitle">Поиск</h2></div><button class="icon-btn" data-close-modal type="button" aria-label="Закрыть">×</button></div><label class="field"><span>Игра или провайдер</span><input id="mobileSearchInput" type="search"></label><div id="mobileSearchResults"></div>`,'#mobileSearchInput');$('#mobileSearchInput').oninput=e=>search(e.target.value,'#mobileSearchResults')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#modalLayer').classList.contains('open'))closeModal();$('#searchResults').classList.remove('open');$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.remove('open')}if(e.key==='/'&&!/input|textarea/i.test(document.activeElement.tagName)&&innerWidth>720){e.preventDefault();$('#globalSearch').focus()}});addEventListener('hashchange',()=>go((location.hash||'#casino').slice(1)));go((location.hash||'#casino').slice(1))}
init();
