const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={route:'casino',filter:'all',provider:'all',favorites:new Set(),sound:true};
const routes={casino:'Casino',wheel:'Wheel',mines:'Mines',classic:'Classic',duels:'Duels',tournaments:'Турниры',trains:'The Trains!',promo:'Промокод',history:'История',help:'Вопросы и ответы'};
const games=[
{id:'crazy-time',name:'Crazy Time',provider:'Evolution Gaming',type:'live',tag:'LIVE',symbol:'CT',g1:'#56315f',g2:'#1d1628'},
{id:'dream-catcher',name:'Dream Catcher',provider:'Evolution Gaming',type:'live',tag:'LIVE',symbol:'DC',g1:'#7258a5',g2:'#23203e'},
{id:'sweet-bonanza',name:'Sweet Bonanza 1000',provider:'Pragmatic Play',type:'hot',tag:'HOT',symbol:'SB',g1:'#9f4771',g2:'#3b244c'},
{id:'mega-wheel',name:'Mega Wheel',provider:'Pragmatic Live',type:'live',tag:'LIVE',symbol:'MW',g1:'#28576e',g2:'#1a2539'},
{id:'dog-house',name:'The Dog House',provider:'Pragmatic Play',type:'hot',tag:'HOT',symbol:'DH',g1:'#86532f',g2:'#302218'},
{id:'gates-olympus',name:'Gates of Olympus',provider:'Pragmatic Play',type:'hot',tag:'',symbol:'Ω',g1:'#62529a',g2:'#27233f'},
{id:'le-bandit',name:'Le Bandit',provider:'Hacksaw',type:'hot',tag:'HOT',symbol:'LB',g1:'#44613b',g2:'#19291d'},
{id:'wanted',name:'Wanted Dead or a Wild',provider:'Hacksaw',type:'hot',tag:'HOT',symbol:'W',g1:'#81513b',g2:'#31221b'},
{id:'money-train',name:'Money Train 4',provider:'Relax Gaming',type:'new',tag:'NEW',symbol:'M4',g1:'#366b76',g2:'#16313b'},
{id:'san-quentin',name:'San Quentin xWays',provider:'No Limit City',type:'new',tag:'NEW',symbol:'SQ',g1:'#665c84',g2:'#28243e'},
{id:'chaos-crew',name:'Chaos Crew II',provider:'Hacksaw',type:'hot',tag:'HOT',symbol:'CC',g1:'#934565',g2:'#38202d'},
{id:'fire-hole',name:'Fire in the Hole 3',provider:'No Limit City',type:'new',tag:'NEW',symbol:'F3',g1:'#956232',g2:'#382718'},
{id:'blackjack',name:'Blackjack VIP',provider:'Pragmatic Live',type:'live',tag:'LIVE',symbol:'21',g1:'#42623c',g2:'#1a2a1e'},
{id:'roulette',name:'Lightning Roulette',provider:'Evolution Gaming',type:'live',tag:'LIVE',symbol:'⚡',g1:'#355a80',g2:'#1e243e'},
{id:'big-bass',name:'Big Bass Splash',provider:'Pragmatic Play',type:'all',tag:'',symbol:'BB',g1:'#3f7766',g2:'#17302e'},
{id:'sugar-rush',name:'Sugar Rush 1000',provider:'Pragmatic Play',type:'new',tag:'NEW',symbol:'SR',g1:'#965275',g2:'#392940'},
{id:'royal-potato',name:'Royal Potato 2',provider:'Hacksaw',type:'new',tag:'NEW',symbol:'RP',g1:'#92642f',g2:'#362516'},
{id:'iron-bank',name:'Iron Bank',provider:'Relax Gaming',type:'all',tag:'',symbol:'IB',g1:'#5d6673',g2:'#20262d'},
{id:'minotaurus',name:'Minotaurus',provider:'PlayNGo',type:'all',tag:'',symbol:'M',g1:'#80503d',g2:'#30211d'},
{id:'voodoo',name:'Voodoo',provider:'Hacksaw',type:'all',tag:'',symbol:'V',g1:'#644887',g2:'#28203c'}
];
const providers=[['4 The Player',15],['Amigo Gaming',144],['Amusnet',419],['Belatra Games',155],['BetSoft',231],['BGaming',294],['Evolution Gaming',141],['Evoplay Entertainment',345],['Hacksaw',245],['NetEnt',240],['No Limit City',136],['PlayNGo',366],['Pragmatic Live',293],['Pragmatic Play',671],['Relax Gaming',115],['Spinomenal',714],['Yggdrasil',184]];
const chats=[['WI','Woom I.','Всем удачи 👋'],['BC','Bogdan C.','Добрый вечер'],['SF','Sanya F.','привет 👋'],['IZ','Izpod W.','Спасибо за дождь']];
const tournaments=[
{name:'SLOTS RACE',prize:'5 000 000 ₽',type:'Slots',status:'Активен',progress:74},
{name:'Slots Tournament',prize:'500 000 ₽',type:'Slots',status:'Сегодня',progress:46},
{name:'Classic Daily',prize:'3 000 ₽',type:'Classic',status:'Ежедневно',progress:31}
];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1800)}
function hashRoute(){return (location.hash.replace(/^#\/?/,'')||'casino').split('?')[0]}
function setRoute(route,push=false){if(!routes[route])route='casino';state.route=route;if(push&&location.hash!==`#/${route}`)location.hash=`#/${route}`;$$('.route-link').forEach(a=>{const on=a.dataset.route===route;a.classList.toggle('active',on);on?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});$('#crumbs').innerHTML=`<span>ZOOMA</span><i>/</i><strong>${routes[route]}</strong>`;$('#sidebar').classList.remove('open');$('#mobileSheet').classList.remove('open');renderRoute(route);scrollTo({top:0,behavior:'auto'})}
function sectionHead(k,t,actions=''){return `<div class="section-head"><div><span class="eyebrow">${k}</span><h2>${t}</h2></div>${actions}</div>`}
function pageHead(k,t,d){return `<div class="page-head"><div><span class="eyebrow">${k}</span><h1>${t}</h1><p>${d}</p></div></div>`}
function gameCard(g){const fav=state.favorites.has(g.id);return `<article class="game-card" data-game="${esc(g.id)}" tabindex="0" role="button" aria-label="Открыть ${esc(g.name)}" style="--g1:${g.g1};--g2:${g.g2}">${g.tag?`<span class="game-tag ${g.tag==='HOT'?'hot':g.tag==='NEW'?'new':''}">${g.tag}</span>`:''}<div class="game-symbol">${esc(g.symbol)}</div><div class="game-meta"><b>${esc(g.name)}</b><small>${esc(g.provider)}${fav?' · ♥':''}</small></div></article>`}
function filteredGames(){return games.filter(g=>(state.filter==='all'||g.type===state.filter||state.filter==='favorites'&&state.favorites.has(g.id))&&(state.provider==='all'||g.provider===state.provider))}
function gamesSection(){const list=filteredGames();return `<section class="section" id="games">${sectionHead('CASINO','Игры',`<div class="game-toolbar">${[['all','Все'],['hot','Популярные'],['new','Новые'],['live','Live'],['favorites','♡ Избранное']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" type="button" data-filter="${v}">${l}</button>`).join('')}</div>`)}<div class="game-grid">${list.length?list.map(gameCard).join(''):`<div class="empty-state" style="grid-column:1/-1"><div><h3>Игр не найдено</h3><p>Сбросьте фильтр или выберите другого провайдера.</p><button class="btn soft" type="button" data-reset>Сбросить</button></div></div>`}</div></section>`}
function providerSection(){return `<section class="provider-block"><div class="provider-head"><div><span class="eyebrow">КАТАЛОГ</span><h2>Провайдеры</h2></div><label class="provider-search"><span>⌕</span><input id="providerSearch" placeholder="Найти провайдера"></label></div><div class="provider-chips" id="providerChips">${providers.map(([n,c])=>`<button class="provider-chip ${state.provider===n?'active':''}" type="button" data-provider="${esc(n)}">${esc(n)}<span>${c}</span></button>`).join('')}</div></section>`}
function renderCasino(){return `<section class="hero-grid"><article class="hero-banner"><div class="hero-copy"><span class="eyebrow">ZOOMA CASINO · REDESIGN</span><h1>Тот же ZOOMA.<br><span>Чище и быстрее.</span></h1><p>Структура исходного lobby сохранена: игровые режимы, турниры, Trains, промокоды, история, FAQ и каталог провайдеров. Интерфейс пересобран с нуля.</p><div class="hero-actions"><button class="btn primary" type="button" data-scroll-games>Открыть каталог</button><a class="btn soft route-link" href="#/tournaments" data-route="tournaments">Турниры</a></div></div></article><div class="hero-stack"><article class="promo-tile violet" data-route-card="trains"><span class="eyebrow">HOT</span><h3>The Trains!</h3><p>Фирменный раздел ZOOMA, вынесенный в отдельный понятный сценарий.</p></article><article class="promo-tile cyan" data-route-card="promo"><span class="eyebrow">PROMO</span><h3>Промокоды</h3><p>Акции и бонусные коды — без смешивания с основным lobby.</p></article></div></section>${gamesSection()}${providerSection()}`}
function modePage(key,title,desc,icon){return `${pageHead('ZOOMA GAME',title,desc)}<div class="cards-2"><article class="info-card"><span class="eyebrow">${key.toUpperCase()}</span><h3>${icon} ${title}</h3><p>В redesign сохранён отдельный маршрут исходного сайта. Игровая механика в демонстрационном прототипе не подключена.</p><div class="metric"><span>Статус</span><strong>UI demo</strong></div></article><article class="info-card"><span class="eyebrow">NAVIGATION</span><h3>Быстрый возврат в Casino</h3><p>Переходы работают через hash-routing и не приводят к 404 на GitHub Pages.</p><div class="hero-actions"><a class="btn soft route-link" href="#/casino" data-route="casino">Вернуться в Casino</a></div></article></div>`}
function renderTournaments(){return `${pageHead('EVENTS','Турниры','Отдельный раздел исходного ZOOMA, пересобранный как понятная лента событий.')}<div class="cards-3">${tournaments.map(t=>`<article class="tournament-card"><span class="eyebrow">${esc(t.status)}</span><h3>${esc(t.name)}</h3><div class="prize">${esc(t.prize)}</div><p class="text-link">${esc(t.type)}</p><div class="progress"><i style="width:${t.progress}%"></i></div><small class="text-link">Демонстрационные данные</small></article>`).join('')}</div>`}
function renderTrains(){return `${pageHead('ZOOMA ORIGINAL','The Trains!','Фирменный раздел сохранён как самостоятельная страница, но визуально приведён к общей системе lobby.')}<div class="cards-3"><article class="info-card"><span class="eyebrow">TRAIN</span><h3>Денежный Train</h3><p>Карточка события с понятным статусом, условиями и точкой входа.</p></article><article class="info-card"><span class="eyebrow">DISCOVERY</span><h3>Активные поезда</h3><p>Список может загружаться из API без перестройки макета.</p></article><article class="info-card"><span class="eyebrow">HISTORY</span><h3>Архив</h3><p>Завершённые события отделены от активных.</p></article></div>`}
function renderPromo(){return `${pageHead('PROMO','Промокод','Сценарий активации промокода вынесен из общего потока и стал проще.')}<div class="cards-2"><article class="info-card"><span class="eyebrow">ACTIVATE</span><h3>Введите промокод</h3><p>Демонстрационная форма без реального начисления.</p><div class="form-grid"><input id="promoInput" maxlength="24" placeholder="PROMOCODE"><button class="btn primary" type="button" data-activate-promo>Активировать</button></div></article><article class="info-card"><span class="eyebrow">RULES</span><h3>Условия рядом</h3><p>Условия акции должны быть видны до активации, а не спрятаны в отдельном сценарии.</p></article></div>`}
function renderHistory(){return `${pageHead('ACCOUNT','История','История действий и игр остаётся отдельным сервисным разделом.')}<div class="empty-state"><div><h3>История пуста</h3><p>В prototype нет подключённого аккаунта.</p><button class="btn soft route-link" type="button" data-route="casino">Открыть Casino</button></div></div>`}
function renderHelp(){const qs=[['Как устроена навигация?','Все основные разделы исходного ZOOMA сохранены в левой панели и мобильном меню.'],['Почему игры не запускаются?','Это redesign prototype. Реальные wagering, депозитные и игровые API намеренно не подключены.'],['Что изменилось на мобильном?','Добавлена нижняя навигация, bottom-sheet для игр и более крупные touch-targets.'],['Где Responsible Gambling?','Юридические и responsible-play ссылки сохранены в footer и должны вести на реальные документы оператора в production.']];return `${pageHead('SUPPORT','Вопросы и ответы','Справка и системные вопросы собраны в одном месте.')}<div class="info-card">${qs.map(([q,a],i)=>`<div class="faq-item"><button type="button" data-faq="${i}"><b>${esc(q)}</b><span>+</span></button><div class="faq-answer">${esc(a)}</div></div>`).join('')}</div>`}
function renderRoute(route){const view=$('#view');const fn={casino:renderCasino,wheel:()=>modePage('wheel','Wheel','Отдельный Wheel-раздел исходного ZOOMA.','◐'),mines:()=>modePage('mines','Mines','Новая версия Mines сохранена как отдельный маршрут.','✣'),classic:()=>modePage('classic','Classic','Классический игровой режим ZOOMA.','◇'),duels:()=>modePage('duels','Duels','Раздел дуэлей из исходной структуры.','⚡'),tournaments:renderTournaments,trains:renderTrains,promo:renderPromo,history:renderHistory,help:renderHelp}[route]||renderCasino;view.innerHTML=fn();view.classList.remove('page-enter');void view.offsetWidth;view.classList.add('page-enter');bindPage()}
function bindPage(){$$('[data-route-card]').forEach(x=>x.onclick=()=>setRoute(x.dataset.routeCard,true));$$('[data-filter]').forEach(x=>x.onclick=()=>{state.filter=x.dataset.filter;renderRoute('casino')});$$('[data-provider]').forEach(x=>x.onclick=()=>{state.provider=state.provider===x.dataset.provider?'all':x.dataset.provider;renderRoute('casino')});$('[data-reset]')?.addEventListener('click',()=>{state.filter='all';state.provider='all';renderRoute('casino')});$('[data-scroll-games]')?.addEventListener('click',()=>$('#games')?.scrollIntoView({behavior:'smooth'}));$('#providerSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('.provider-chip').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q))});$$('[data-game]').forEach(card=>{const open=()=>openGame(card.dataset.game);card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});$('[data-activate-promo]')?.addEventListener('click',()=>toast($('#promoInput')?.value.trim()?'Промокод принят в demo-режиме':'Введите промокод'));$$('[data-faq]').forEach(b=>b.onclick=()=>b.closest('.faq-item').classList.toggle('open'));$$('.route-link,[data-route]').forEach(bindRouteLink)}
function bindRouteLink(a){if(a.dataset.bound)return;a.dataset.bound='1';a.addEventListener('click',e=>{if(!a.dataset.route)return;e.preventDefault();setRoute(a.dataset.route,true)})}
function openGame(id){const g=games.find(x=>x.id===id);if(!g)return;openModal(`<div class="modal-head"><div><span class="eyebrow">${esc(g.provider)}</span><h2>${esc(g.name)}</h2></div><button class="icon-btn" type="button" data-close-modal>×</button></div><p>Карточка игры работает как navigation/detail layer. Запуск реальной игры и wagering в prototype не подключены.</p><div class="hero-actions"><button class="btn soft" type="button" data-favorite="${esc(g.id)}">${state.favorites.has(g.id)?'Убрать из избранного':'Добавить в избранное'}</button></div>`);$('[data-favorite]')?.addEventListener('click',e=>{const v=e.currentTarget.dataset.favorite;state.favorites.has(v)?state.favorites.delete(v):state.favorites.add(v);closeModal();if(state.route==='casino')renderRoute('casino');toast('Избранное обновлено')})}
function openModal(html){$('#modalContent').innerHTML=html;$('#modalLayer').classList.add('open');$('#modalLayer').setAttribute('aria-hidden','false');$('[data-close-modal]','#modalContent')?.addEventListener('click',closeModal)}
function closeModal(){$('#modalLayer').classList.remove('open');$('#modalLayer').setAttribute('aria-hidden','true')}
function modalTemplate(type){const m={login:['Войти','Вход в prototype не подключён.'],register:['Создать аккаунт','Регистрация показана как UI-сценарий без отправки данных.'],support:['Поддержка','Для production здесь должен использоваться реальный канал поддержки оператора.']}[type]||['ZOOMA','Демонстрационное окно'];return `<div class="modal-head"><div><span class="eyebrow">ZOOMA</span><h2>${m[0]}</h2></div><button class="icon-btn" type="button" data-close-modal>×</button></div><p>${m[1]}</p><div class="form-grid"><input placeholder="Email" type="email"><input placeholder="Пароль" type="password"><button class="btn primary" type="button" data-demo-submit>Продолжить</button></div>`}
function renderSearch(q){const box=$('#searchPopover');const query=q.trim().toLowerCase();if(!query){box.classList.remove('open');box.innerHTML='';return}const rs=[...games.filter(g=>(g.name+' '+g.provider).toLowerCase().includes(query)).slice(0,7).map(g=>({label:g.name,meta:g.provider,game:g.id})),...Object.entries(routes).filter(([,label])=>label.toLowerCase().includes(query)).slice(0,4).map(([route,label])=>({label,meta:'Раздел',route}))];box.innerHTML=rs.length?rs.map((r,i)=>`<button class="search-result" type="button" data-search-index="${i}"><b>${esc(r.label)}</b><small>${esc(r.meta)}</small></button>`).join(''):`<div class="search-result"><b>Ничего не найдено</b></div>`;box.classList.add('open');$$('[data-search-index]',box).forEach((b,i)=>b.onclick=()=>{const r=rs[i];box.classList.remove('open');if(r.game)openGame(r.game);else setRoute(r.route,true)})}
function init(){$$('.route-link').forEach(bindRouteLink);$$('[data-modal]').forEach(b=>b.onclick=()=>{openModal(modalTemplate(b.dataset.modal));$('[data-demo-submit]')?.addEventListener('click',()=>toast('Демо: данные не отправляются'))});$$('[data-demo-action]').forEach(b=>b.onclick=()=>toast('Демо-режим: финансовые операции не подключены'));$('[data-close-modal]','#modalLayer')?.addEventListener('click',closeModal);$('#modalLayer').addEventListener('click',e=>{if(e.target.hasAttribute('data-close-modal'))closeModal()});$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#mobileGames').onclick=()=>{$('#mobileSheet').classList.add('open');$('#mobileSheet').setAttribute('aria-hidden','false')};$('#sheetClose').onclick=()=>{$('#mobileSheet').classList.remove('open');$('#mobileSheet').setAttribute('aria-hidden','true')};$('#chatToggle').onclick=()=>$('#chatDrawer').classList.add('open');$('#chatClose').onclick=()=>$('#chatDrawer').classList.remove('open');$('#soundToggle').onclick=()=>{state.sound=!state.sound;$('#soundState').textContent=state.sound?'ON':'OFF'};$('#globalSearch').addEventListener('input',e=>renderSearch(e.target.value));document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('#globalSearch').focus();if(innerWidth<620)$('.topbar').classList.add('search-open')}if(e.key==='Escape'){closeModal();$('#chatDrawer').classList.remove('open');$('#searchPopover').classList.remove('open')}});$('#chatList').innerHTML=chats.map(([a,n,m])=>`<div class="chat-message"><div class="chat-avatar">${a}</div><div><b>${esc(n)}</b><p>${esc(m)}</p></div></div>`).join('');window.addEventListener('hashchange',()=>setRoute(hashRoute()));setRoute(hashRoute())}
init();
