const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={route:'casino',filter:'all',provider:'all',favorites:new Set(),sound:true};
const routes={casino:'Casino',wheel:'Wheel',mines:'Mines',classic:'Classic',duels:'Duels',tournaments:'Турниры',trains:'The Trains!',promo:'Промокод',history:'История',help:'FAQ'};
const games=[
{id:'crazy-time',name:'Crazy Time',provider:'Evolution Gaming',type:'live',tag:'LIVE',symbol:'CT',g1:'#6e405b',g2:'#211524'},
{id:'dream-catcher',name:'Dream Catcher',provider:'Evolution Gaming',type:'live',tag:'LIVE',symbol:'DC',g1:'#6856a8',g2:'#1d1b38'},
{id:'sweet-bonanza',name:'Sweet Bonanza 1000',provider:'Pragmatic Play',type:'hot',tag:'HOT',symbol:'SB',g1:'#ad4f7a',g2:'#3b1d35'},
{id:'mega-wheel',name:'Mega Wheel',provider:'Pragmatic Live',type:'live',tag:'LIVE',symbol:'MW',g1:'#28667d',g2:'#142b3a'},
{id:'dog-house',name:'The Dog House',provider:'Pragmatic Play',type:'hot',tag:'HOT',symbol:'DH',g1:'#985b34',g2:'#362013'},
{id:'gates-olympus',name:'Gates of Olympus',provider:'Pragmatic Play',type:'hot',tag:'',symbol:'Ω',g1:'#715db0',g2:'#282140'},
{id:'le-bandit',name:'Le Bandit',provider:'Hacksaw',type:'hot',tag:'HOT',symbol:'LB',g1:'#4f743f',g2:'#18271b'},
{id:'wanted',name:'Wanted Dead or a Wild',provider:'Hacksaw',type:'hot',tag:'HOT',symbol:'W',g1:'#8d583f',g2:'#2e1d18'},
{id:'money-train',name:'Money Train 4',provider:'Relax Gaming',type:'new',tag:'NEW',symbol:'M4',g1:'#34717f',g2:'#15333b'},
{id:'san-quentin',name:'San Quentin xWays',provider:'No Limit City',type:'new',tag:'NEW',symbol:'SQ',g1:'#645c85',g2:'#242139'},
{id:'chaos-crew',name:'Chaos Crew II',provider:'Hacksaw',type:'hot',tag:'HOT',symbol:'CC',g1:'#9b486c',g2:'#341b2a'},
{id:'fire-hole',name:'Fire in the Hole 3',provider:'No Limit City',type:'new',tag:'NEW',symbol:'F3',g1:'#9d6b36',g2:'#332514'},
{id:'blackjack',name:'Blackjack VIP',provider:'Pragmatic Live',type:'live',tag:'LIVE',symbol:'21',g1:'#4a6b42',g2:'#19291d'},
{id:'roulette',name:'Lightning Roulette',provider:'Evolution Gaming',type:'live',tag:'LIVE',symbol:'⚡',g1:'#3a6691',g2:'#1d2741'},
{id:'big-bass',name:'Big Bass Splash',provider:'Pragmatic Play',type:'all',tag:'',symbol:'BB',g1:'#3f806c',g2:'#18302c'},
{id:'sugar-rush',name:'Sugar Rush 1000',provider:'Pragmatic Play',type:'new',tag:'NEW',symbol:'SR',g1:'#9e557b',g2:'#37263e'},
{id:'royal-potato',name:'Royal Potato 2',provider:'Hacksaw',type:'new',tag:'NEW',symbol:'RP',g1:'#956431',g2:'#362417'},
{id:'iron-bank',name:'Iron Bank',provider:'Relax Gaming',type:'all',tag:'',symbol:'IB',g1:'#626d7b',g2:'#20262d'},
{id:'minotaurus',name:'Minotaurus',provider:'PlayNGo',type:'all',tag:'',symbol:'M',g1:'#865441',g2:'#30211d'},
{id:'voodoo',name:'Voodoo',provider:'Hacksaw',type:'all',tag:'',symbol:'V',g1:'#68498d',g2:'#281f3c'}];
const providers=[['Pragmatic Play',671],['Evolution Gaming',141],['Hacksaw',245],['Pragmatic Live',293],['Relax Gaming',115],['No Limit City',136],['PlayNGo',366],['NetEnt',240],['BGaming',294],['Spinomenal',714]];
const tournaments=[{id:'slots-race',name:'SLOTS RACE',prize:'5 000 000 ₽',kind:'Slots',progress:74},{id:'slots-tournament',name:'Slots Tournament',prize:'500 000 ₽',kind:'Slots',progress:46},{id:'classic-daily',name:'Classic Daily',prize:'3 000 ₽',kind:'Classic',progress:31}];
const historyItems=[['Сегодня','Crazy Time','Открыта карточка игры'],['Сегодня','Pragmatic Play','Фильтр провайдера'],['Вчера','The Trains!','Открыт раздел события']];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)}
function routeFromHash(){return (location.hash.replace(/^#\/?/,'')||'casino').split('?')[0]}
function navigate(route){if(!routes[route])route='casino';if(location.hash!==`#/${route}`)location.hash=`#/${route}`;else setRoute(route)}
function setRoute(route){if(!routes[route])route='casino';state.route=route;$$('.route-link').forEach(a=>{const on=a.dataset.route===route;a.classList.toggle('active',on);on?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});$('#routeLabel').textContent=routes[route].toUpperCase();renderRoute(route);window.scrollTo({top:0,behavior:'auto'});$('#view').focus({preventScroll:true})}
function head(k,t,d){return `<header class="page-head"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${d}</p></header>`}
function btn(label,attrs=''){return `<button class="btn" type="button" ${attrs}>${label}</button>`}
function gameCard(g){const fav=state.favorites.has(g.id);return `<article class="game-card" data-game="${g.id}" tabindex="0" role="button" aria-label="Открыть ${esc(g.name)}" style="--g1:${g.g1};--g2:${g.g2}">${g.tag?`<span class="tag">${g.tag}</span>`:''}<button class="fav" type="button" data-fav="${g.id}" aria-label="${fav?'Убрать из избранного':'Добавить в избранное'}">${fav?'♥':'♡'}</button><div class="symbol">${esc(g.symbol)}</div><div class="meta"><b>${esc(g.name)}</b><small>${esc(g.provider)}</small></div></article>`}
function filteredGames(){return games.filter(g=>(state.filter==='all'||g.type===state.filter||state.filter==='favorites'&&state.favorites.has(g.id))&&(state.provider==='all'||g.provider===state.provider))}
function gamesBlock(){const list=filteredGames();return `<section class="section" id="catalog"><div class="section-head"><div><span class="eyebrow">DISCOVER</span><h2>Игровой поток</h2><p>${state.provider==='all'?'Все провайдеры':`Провайдер: ${esc(state.provider)}`}</p></div><div class="chips">${[['all','Все'],['hot','Hot'],['new','New'],['live','Live'],['favorites','♥ Saved']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" data-filter="${v}" type="button">${l}</button>`).join('')}</div></div><div class="game-grid">${list.length?list.map(gameCard).join(''):`<div class="panel-card"><h3>Ничего не найдено</h3><p>Сбросьте фильтр или выберите другого провайдера.</p>${btn('Сбросить','data-reset')}</div>`}</div></section>`}
function providerBlock(){return `<section class="section"><div class="section-head"><div><span class="eyebrow">STUDIOS</span><h2>Провайдеры как быстрый фильтр</h2></div>${state.provider!=='all'?btn('Сбросить провайдера','data-provider="all"'):''}</div><div class="provider-strip">${providers.map(([n,c])=>`<button class="provider-card ${state.provider===n?'active':''}" data-provider="${esc(n)}" type="button"><b>${esc(n)}</b><small>${c} games</small></button>`).join('')}</div></section>`}
function renderCasino(){return `<div class="page-shell"><section class="hero-stage"><article class="feature-card feature-main"><div class="feature-copy"><span class="eyebrow">ZOOMA / REBUILT</span><h1>PLAY<br><span>YOUR WAY.</span></h1><p>Исходная структура ZOOMA сохранена, но интерфейс больше не повторяет старое lobby: разделы стали игровыми “мирами”, поиск — command palette, детали — slide-over panels.</p><div class="actions"><button class="btn primary" type="button" data-scroll-catalog>Открыть игры</button><button class="btn" type="button" data-open-palette>Найти игру</button></div></div></article><div class="feature-stack"><article class="world-card trains" data-route-card="trains" tabindex="0" role="button"><span class="eyebrow">ORIGINAL MODE</span><h3>The Trains!</h3><p>Отдельный мир с событиями и быстрым входом.</p><div class="world-mark">➤</div></article><article class="world-card promo" data-route-card="promo" tabindex="0" role="button"><span class="eyebrow">BONUS HUB</span><h3>Промокод</h3><p>Активация, условия и история — в одном сценарии.</p><div class="world-mark">%</div></article></div></section>${gamesBlock()}${providerBlock()}</div>`}
const modeConfig={wheel:['LIVE MODE','Wheel','Живой режим вынесен в отдельный immersive-stage.','◐','#5de7ff'],mines:['RISK GRID','Mines','Минималистичный экран режима с отдельной логикой и контролами.','✣','#c6ff43'],classic:['ARCADE','Classic','Классические режимы собраны как отдельная коллекция.','◇','#9a75ff'],duels:['PVP','Duels','Сценарий дуэлей отделён от общего каталога и получает собственный статус.','⚡','#ff6fb0']};
function renderMode(route){const [k,t,d,icon,color]=modeConfig[route];return `${head(k,t,d)}<div class="mode-layout"><article class="mode-stage" style="--mode:${color}"><div class="mode-orb"></div><div class="mode-symbol">${icon}</div><div><span class="eyebrow">${k}</span><h2>${t}</h2><p>Это полноценный кликабельный UI-экран прототипа. Реальная игровая механика не подключена.</p><div class="actions"><button class="btn primary" type="button" data-demo="${route}">Открыть демо-сценарий</button><a class="btn route-link" href="#/casino" data-route="casino">В Casino</a></div></div></article><aside class="mode-side stack"><div class="panel-card"><span class="eyebrow">STATUS</span><h3>Ready UI</h3><div class="metric"><span>Route</span><strong>#/${route}</strong></div><div class="metric"><span>Keyboard</span><strong>Enabled</strong></div></div><div class="panel-card"><span class="eyebrow">NEXT</span><h3>Связанные разделы</h3><div class="actions"><button class="btn" data-nav="tournaments">Events</button><button class="btn" data-nav="history">History</button></div></div></aside></div>`}
function renderTournaments(){return `${head('EVENTS','Турниры','События стали отдельным dashboard вместо ещё одной строки в старом sidebar.')}<div class="event-grid">${tournaments.map(t=>`<article class="event-card" data-event="${t.id}" tabindex="0" role="button"><span class="eyebrow">${esc(t.kind)}</span><h3>${esc(t.name)}</h3><div class="prize">${esc(t.prize)}</div><p>Открыть детали события</p><div class="progress"><i style="width:${t.progress}%"></i></div></article>`).join('')}</div>`}
function renderTrains(){return `${head('ZOOMA ORIGINAL','The Trains!','В новом интерфейсе фирменный режим стал визуальным event-world, а не ещё одним пунктом меню.')}<div class="mode-layout"><article class="mode-stage" style="--mode:#ff9f58"><div class="mode-orb"></div><div class="mode-symbol">➤</div><div><span class="eyebrow">ACTIVE TRACK</span><h2>Train 07</h2><p>Демонстрационный event-state с отдельными деталями, историей и быстрыми действиями.</p><div class="actions"><button class="btn primary" type="button" data-train-detail>Открыть Train</button><button class="btn" type="button" data-nav="history">История</button></div></div></article><aside class="mode-side stack"><div class="panel-card"><span class="eyebrow">QUEUE</span><h3>Следующие поезда</h3><div class="metric"><span>Train 08</span><strong>soon</strong></div><div class="metric"><span>Train 09</span><strong>queued</strong></div></div><div class="panel-card"><span class="eyebrow">RULES</span><p>В production сюда подключается реальная event-модель.</p></div></aside></div>`}
function renderPromo(){return `${head('BONUS HUB','Промокод','Активация теперь не выглядит отдельным системным окном — это полноценный понятный сценарий.')}<div class="promo-layout"><article class="panel-card"><span class="eyebrow">ACTIVATE</span><h2>Введите код</h2><p>Проверка формата работает в прототипе. Начисления не подключены.</p><div class="promo-input"><input id="promoInput" maxlength="24" placeholder="ZOOMA2026"><button class="btn primary" type="button" data-promo-activate>Активировать</button></div></article><aside class="panel-card"><span class="eyebrow">RECENT</span><h3>Последние действия</h3><div class="metric"><span>WELCOME</span><strong>viewed</strong></div><div class="metric"><span>RACE</span><strong>available</strong></div></aside></div>`}
function renderHistory(){return `${head('ACCOUNT','История','Отдельный сервисный экран с фильтрами и detail-state.')}<div class="history-layout"><article class="panel-card"><div class="section-head"><div><span class="eyebrow">ACTIVITY</span><h2>Последние действия</h2></div><div class="chips"><button class="chip active" type="button" data-history-filter="all">Все</button><button class="chip" type="button" data-history-filter="games">Игры</button></div></div><div class="history-list" id="historyList">${historyItems.map(([d,t,s])=>`<button class="history-row" type="button" data-history-item="${esc(t)}"><small>${d}</small><span><b>${esc(t)}</b><small>${esc(s)}</small></span><strong>→</strong></button>`).join('')}</div></article><aside class="panel-card"><span class="eyebrow">ACCOUNT</span><h3>Demo profile</h3><p>История, избранное и профиль уже имеют интерактивные состояния.</p><button class="btn" type="button" data-account>Открыть аккаунт</button></aside></div>`}
function renderHelp(){const faq=[['Как искать игру?','Нажмите иконку поиска или клавишу /. Откроется глобальный command palette.'],['Карточки игр кликабельны?','Да. Карточка открывает detail drawer, сердечко переключает избранное.'],['Работают ли разделы Wheel / Mines / Classic / Duels?','Да, каждый имеет отдельный route и UI-state. Реальная игровая механика не подключена.'],['Где провайдеры?','Они работают как быстрый фильтр каталога и доступны из Casino и верхнего service-nav.']];return `${head('SUPPORT','FAQ','Справка теперь тоже кликабельная, без тупиковых ссылок.')}<div class="help-layout"><article class="panel-card">${faq.map(([q,a],i)=>`<div class="faq-item"><button type="button" data-faq="${i}"><b>${esc(q)}</b><span>+</span></button><div class="faq-answer">${esc(a)}</div></div>`).join('')}</article><aside class="panel-card"><span class="eyebrow">SUPPORT</span><h3>Нужна помощь?</h3><p>Откройте support drawer — там работают demo-действия.</p><button class="btn primary" type="button" data-support>Открыть поддержку</button></aside></div>`}
function renderRoute(r){const out=r==='casino'?renderCasino():modeConfig[r]?renderMode(r):r==='tournaments'?renderTournaments():r==='trains'?renderTrains():r==='promo'?renderPromo():r==='history'?renderHistory():renderHelp();$('#view').innerHTML=out;bindPage()}
function openDrawer(html){$('#drawerPanel').innerHTML=html;$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden';$('#drawerPanel [data-drawer-close-btn]')?.focus()}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');document.documentElement.style.overflow=''}
function drawerHead(title){return `<div class="drawer-head"><h2>${esc(title)}</h2><button class="drawer-close" type="button" data-drawer-close-btn>×</button></div>`}
function openGame(id){const g=games.find(x=>x.id===id);if(!g)return;openDrawer(`${drawerHead(g.name)}<div class="drawer-card" style="background:linear-gradient(145deg,${g.g1},${g.g2})"><span class="eyebrow">${esc(g.tag||'GAME')}</span><h2 style="font-size:42px;margin:10px 0">${esc(g.symbol)}</h2><p>${esc(g.provider)}</p></div><div class="drawer-section"><div class="drawer-card"><b>Game detail</b><p>Полноценное detail-state вместо неработающей карточки. Реальный launcher API в prototype не подключён.</p><button class="btn primary" type="button" data-demo-play="${g.id}">Demo action</button></div><div class="drawer-card"><b>Provider</b><p>${esc(g.provider)}</p><button class="btn" type="button" data-provider-open="${esc(g.provider)}">Показать игры провайдера</button></div></div>`)}
function openAccount(){openDrawer(`${drawerHead('Account')}<div class="drawer-section"><div class="drawer-card"><span class="eyebrow">DEMO PROFILE</span><h3>ZOOMA ID</h3><p>Избранное: ${state.favorites.size}</p><button class="btn" data-account-action="login">Войти</button></div><div class="drawer-card"><b>Quick actions</b><div class="actions"><button class="btn primary" data-account-action="deposit">Deposit</button><button class="btn" data-account-action="history">History</button></div></div><div class="drawer-card"><b>Sound</b><button class="btn" data-sound-toggle>${state.sound?'ON':'OFF'}</button></div></div>`)}
function openSupport(){openDrawer(`${drawerHead('Support')}<div class="drawer-section"><div class="drawer-card"><b>Live chat</b><p>Демо support-state.</p><button class="btn primary" data-support-action="chat">Открыть demo chat</button></div><div class="drawer-card"><b>Email</b><p>support@zooma.casino</p><button class="btn" data-support-action="copy">Скопировать</button></div></div>`)}
function openEvent(id){const t=tournaments.find(x=>x.id===id);if(!t)return;openDrawer(`${drawerHead(t.name)}<div class="drawer-card"><span class="eyebrow">${esc(t.kind)}</span><h2>${esc(t.prize)}</h2><p>Progress ${t.progress}%</p><div class="progress"><i style="width:${t.progress}%"></i></div></div><div class="drawer-card"><b>Event details</b><p>Детали события открываются в отдельной панели. Данные демонстрационные.</p><button class="btn primary" data-event-action>Понятно</button></div>`)}
function openProviders(){openDrawer(`${drawerHead('Providers')}<div class="drawer-section">${providers.map(([n,c])=>`<button class="provider-card ${state.provider===n?'active':''}" data-provider-drawer="${esc(n)}"><b>${esc(n)}</b><small>${c} games</small></button>`).join('')}<button class="btn" data-provider-drawer="all">Все провайдеры</button></div>`)}
function openPalette(){const p=$('#palette');p.classList.add('open');p.setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden';$('#paletteInput').value='';renderSearch('');setTimeout(()=>$('#paletteInput').focus(),20)}
function closePalette(){$('#palette').classList.remove('open');$('#palette').setAttribute('aria-hidden','true');document.documentElement.style.overflow=''}
function renderSearch(value){const q=value.trim().toLowerCase();const routeItems=Object.entries(routes).map(([id,name])=>({kind:'route',id,name,meta:'Раздел'}));const gameItems=games.map(g=>({kind:'game',id:g.id,name:g.name,meta:g.provider}));const providerItems=providers.map(([name,count])=>({kind:'provider',id:name,name,meta:`${count} games`}));const all=[...routeItems,...gameItems,...providerItems];const out=(q?all.filter(x=>(x.name+' '+x.meta).toLowerCase().includes(q)):all.slice(0,10)).slice(0,12);$('#paletteResults').innerHTML=out.length?out.map(x=>`<button class="search-result" type="button" data-search-kind="${x.kind}" data-search-id="${esc(x.id)}"><span><b>${esc(x.name)}</b><small style="display:block">${esc(x.meta)}</small></span><span>↗</span></button>`).join(''):`<div class="drawer-card">Ничего не найдено</div>`}
function bindPage(){
$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderRoute('casino')});
$$('[data-provider]').forEach(b=>b.onclick=()=>{state.provider=b.dataset.provider;renderRoute('casino')});
$$('[data-game]').forEach(c=>{c.onclick=e=>{if(e.target.closest('[data-fav]'))return;openGame(c.dataset.game)};c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openGame(c.dataset.game)}}});
$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);toast(state.favorites.has(id)?'Добавлено в избранное':'Удалено из избранного');if(state.route==='casino')renderRoute('casino')});
$('[data-scroll-catalog]')?.addEventListener('click',()=>$('#catalog')?.scrollIntoView({behavior:'smooth'}));
$('[data-open-palette]')?.addEventListener('click',openPalette);
$$('[data-route-card]').forEach(c=>{c.onclick=()=>navigate(c.dataset.routeCard);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();navigate(c.dataset.routeCard)}}});
$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));
$$('[data-demo]').forEach(b=>b.onclick=()=>toast(`${routes[b.dataset.demo]}: demo UI открыт`));
$$('[data-event]').forEach(c=>{c.onclick=()=>openEvent(c.dataset.event);c.onkeydown=e=>{if(e.key==='Enter')openEvent(c.dataset.event)}});
$('[data-train-detail]')?.addEventListener('click',()=>openDrawer(`${drawerHead('Train 07')}<div class="drawer-card"><span class="eyebrow">ACTIVE TRACK</span><h2>Train 07</h2><p>Демонстрационный detail-state события.</p></div><div class="drawer-card"><button class="btn primary" data-event-action>Закрыть detail</button></div>`));
$('[data-promo-activate]')?.addEventListener('click',()=>{const v=$('#promoInput').value.trim();if(v.length<4){toast('Введите минимум 4 символа');return}toast(`Код ${v.toUpperCase()} проверен · demo`)});
$$('[data-history-item]').forEach(b=>b.onclick=()=>openDrawer(`${drawerHead('History detail')}<div class="drawer-card"><b>${esc(b.dataset.historyItem)}</b><p>Демонстрационная запись истории.</p></div>`));
$$('[data-history-filter]').forEach(b=>b.onclick=()=>{$$('[data-history-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`Фильтр: ${b.textContent.trim()}`)});
$('[data-account]')?.addEventListener('click',openAccount);$('[data-support]')?.addEventListener('click',openSupport);
$$('[data-faq]').forEach(b=>b.onclick=()=>b.closest('.faq-item').classList.toggle('open'));
}
function bindGlobal(){
$$('.route-link').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();navigate(a.dataset.route)}));
$('#openSearch').onclick=openPalette;$('#mobileSearch').onclick=openPalette;$('#openAccount').onclick=openAccount;$('#mobileAccount').onclick=openAccount;$('#providerQuick').onclick=openProviders;
$('#mobileExplore').onclick=()=>openDrawer(`${drawerHead('Explore')}<div class="drawer-section">${Object.entries(routes).filter(([k])=>!['casino','history','help'].includes(k)).map(([k,v])=>`<button class="provider-card" data-drawer-route="${k}"><b>${v}</b><small>Открыть раздел</small></button>`).join('')}</div>`);
$$('[data-drawer-close]').forEach(b=>b.onclick=closeDrawer);$$('[data-palette-close]').forEach(b=>b.onclick=closePalette);
$('#paletteInput').addEventListener('input',e=>renderSearch(e.target.value));
$('#paletteResults').addEventListener('click',e=>{const b=e.target.closest('[data-search-kind]');if(!b)return;const {searchKind:k,searchId:id}=b.dataset;closePalette();if(k==='route')navigate(id);else if(k==='game')openGame(id);else{state.provider=id;navigate('casino')}});
$('#drawerPanel').addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(t.matches('[data-drawer-close-btn]'))closeDrawer();if(t.matches('[data-demo-play]'))toast('Game launcher не подключён в prototype');if(t.matches('[data-provider-open]')){state.provider=t.dataset.providerOpen;closeDrawer();navigate('casino')}if(t.matches('[data-provider-drawer]')){state.provider=t.dataset.providerDrawer;closeDrawer();navigate('casino')}if(t.matches('[data-account-action="history"]')){closeDrawer();navigate('history')}if(t.matches('[data-account-action="deposit"]'))toast('Deposit: demo state');if(t.matches('[data-account-action="login"]'))toast('Login: demo state');if(t.matches('[data-sound-toggle]')){state.sound=!state.sound;t.textContent=state.sound?'ON':'OFF';toast(`Sound ${state.sound?'ON':'OFF'}`)}if(t.matches('[data-support-action="chat"]'))toast('Demo chat открыт');if(t.matches('[data-support-action="copy"]')){navigator.clipboard?.writeText('support@zooma.casino');toast('Email скопирован')}if(t.matches('[data-event-action]'))closeDrawer();if(t.matches('[data-drawer-route]')){closeDrawer();navigate(t.dataset.drawerRoute)}});
$$('[data-doc]').forEach(b=>b.onclick=()=>openDrawer(`${drawerHead(b.dataset.doc)}<div class="drawer-card"><p>В production здесь должен быть официальный документ оператора. В prototype показывается только UI-state.</p></div>`));
window.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();openPalette()}if(e.key==='Escape'){closePalette();closeDrawer()}});
window.addEventListener('hashchange',()=>setRoute(routeFromHash()));
}
bindGlobal();setRoute(routeFromHash());
